---
# tasks file for harbor

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Check if harbor parent directory exists
  stat:
    path: "{{ harbor_parent_dir }}"
  register: harbor_parent_dir_check

- name: Check if harbor is installed already
  stat:
    path: "{{ harbor_parent_dir }}/harbor/installed-indicator"
  register: harbor_installed_check

- name: Install Harbor
  ansible.builtin.import_tasks:
    file: install.yml
  run_once: true
  when:
    - not harbor_installed_check.stat.exists
    - not harbor_force_install

- name: Force Install Harbor
  ansible.builtin.import_tasks:
    file: install.yml
  run_once: true
  when:
    - harbor_force_install
