---
- name: TLS | Creating TLS Directory
  ansible.builtin.file:
    path: "{{ harbor_parent_dir }}/harbor/tls"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: TLS | Creating Private Key
  community.crypto.openssl_privatekey:
    path: "{{ harbor_parent_dir }}/harbor/tls/certificate.key"

- name: TLS | Creating Self-Signed Certificate
  community.crypto.x509_certificate:
    path: "{{ harbor_parent_dir }}/harbor/tls/certificate.pem"
    privatekey_path: "{{ harbor_parent_dir }}/harbor/tls/certificate.key"
    provider: selfsigned