---
- name: Compose | Stopping Compose
  community.docker.docker_compose_v2:
    project_src: "{{ harbor_parent_dir }}/harbor"
    state: absent

- name: Compose | Reading docker-compose.yml
  ansible.builtin.slurp:
    src: "{{ harbor_parent_dir }}/harbor/docker-compose.yml"
  register: docker_compose_yml

- name: Compose | Converting To Dictionary
  ansible.builtin.set_fact:
    docker_compose_yml: "{{ docker_compose_yml['content'] | b64decode | from_yaml }}"

- name: Compose | Openning Only For One IP
  ansible.builtin.set_fact:
    docker_compose_yml: "{{ docker_compose_yml | combine(newdata, recursive=True) }}"
  vars: 
    newdata:
      services:
        proxy:
          ports:
            - "{{ harbor_iface_ip }}:{{ harbor_https_port }}:8443"

- name: Compose | Writing docker-compose.yml
  ansible.builtin.copy:
    content: '{{ docker_compose_yml | to_nice_yaml(indent=2) }}'
    dest: "{{ harbor_parent_dir }}/harbor/docker-compose.yml"

- name:  Compose | Starting Compose
  community.docker.docker_compose_v2:
    project_src: "{{ harbor_parent_dir }}/harbor"
    state: present